# Generated by Django 5.2.17 on 2026-08-14 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KarnatakaAgroZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Western Ghats, Southern Maidan', max_length=100)),
                ('soil_profile', models.CharField(max_length=100)),
                ('min_rainfall_mm', models.IntegerField()),
                ('max_rainfall_mm', models.IntegerField()),
                ('base_elevation_m', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SpeciesConstraint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('type', models.CharField(choices=[('TREE', 'Tree'), ('CROP', 'Crop')], max_length=4)),
                ('drought_tolerance', models.IntegerField(help_text='Scale 1-10 (10 being highly tolerant)')),
                ('soil_ph_min', models.DecimalField(decimal_places=1, max_digits=3)),
                ('soil_ph_max', models.DecimalField(decimal_places=1, max_digits=3)),
                ('commercial_value', models.TextField(help_text='Agro-commercial uses and ecosystem services')),
                ('target_zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='decision_support.karnatakaagrozone')),
            ],
        ),
    ]
