# Generated by Django 5.2.17 on 2026-08-14 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decision_support', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='speciesconstraint',
            name='carbon_rating',
            field=models.IntegerField(default=5, help_text='Scale 1-10 for CO2 absorption'),
        ),
        migrations.AddField(
            model_name='speciesconstraint',
            name='ideal_temp_max_c',
            field=models.FloatField(default=35.0),
        ),
        migrations.AddField(
            model_name='speciesconstraint',
            name='ideal_temp_min_c',
            field=models.FloatField(default=15.0),
        ),
        migrations.AddField(
            model_name='speciesconstraint',
            name='max_elevation_m',
            field=models.IntegerField(default=3000),
        ),
        migrations.AddField(
            model_name='speciesconstraint',
            name='min_elevation_m',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='karnatakaagrozone',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='speciesconstraint',
            name='commercial_value',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='speciesconstraint',
            name='drought_tolerance',
            field=models.IntegerField(help_text='Scale 1-10'),
        ),
        migrations.AlterField(
            model_name='speciesconstraint',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='speciesconstraint',
            name='soil_ph_max',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='speciesconstraint',
            name='soil_ph_min',
            field=models.FloatField(),
        ),
    ]
