services:
  - type: web
    name: terraguard
    env: python
    buildCommand: "pip install -r requirements.txt && python terraguard/manage.py collectstatic --no-input && python terraguard/manage.py migrate && python terraguard/manage.py seed_data"
    startCommand: "cd terraguard && gunicorn terraguard.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
